apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ if eq .Values.ingress.path "/" }}"/actuator/prometheus"{{ else }}"{{ .Values.ingress.path }}/actuator/prometheus"{{ end }}
    prometheus.io/port: {{ .Values.containers.port | quote }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 80
      targetPort: {{ .Values.containers.port }}
  selector:
    app: {{ .Release.Name }}
